endpoint:  https://...
create_user:
  users:
    - id: user_1
      name: Name Lastname
      group: EvmGroup-super_administrator
  default_password: default_pass
create_tenant:
  tenants:
    - name: Test
      description: 'Test Project'
      parent: DefaultTenantName
    - name: Test2
      description: 'Test Project2'
      parent: DefaultTenantName
create_groups:
  groups:
    - name: CRFGroup-admin_self_service
      role: EvmRole-user_self_service
      tenant: DefaultTenantName
      tags: '""'
